### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by nivle1661** [FLIR/BosonUSB#2]
Do you know if there is a way to get the exact timestamp of when the images are taken, rather then when the images are received from the buffer?
Thanks!

**Comment by ghost** [comment]
There is a double NO answer:
- It is not a timestamp, it is a frame count. This information is in the telemetry line.
- however, the telemetry line is not sent using the USBvideo.

So unfortunately, right now, the option is to do sync based on input drivers.

**Comment by ghost** [comment]
If you are using our ADAS kits then this is the answer:
- Current ADAS GMSL kit includes a telemetry line but it is not useful since is losing two bits. (It works for other matters, but not for the one you are asking)
- Current ADAS USB includes FrameCount, Timestamp and status flags

In the future standard Boson builds will include telemetry in the USB, but not today.

**Comment by espadolini** [comment]
Do you have an ETA for when a boson firmware that can output the telemetry data via USB will be available?
