### ISSUE TITLE
Stream capture over network

### ISSUE THREAD

**Issue by vgrsystems** [FLIR/BosonUSB#4]
Good evening,
Not really an issue because the code works very well, even on a raspberry. Nevertheless, I need to stream the video over network with udp and H264 compression.
Do you have any ideas how to do this inside your code ?
I tried gstreamer and V4L2 drivers but the quality and latency are too bad.

Thank you very much for your help,
Regards,

François

**Comment by ghost** [comment]
Thanks for nice comments. 
Your approach sounds the correct one to me :  V4Linux + gstreamer. (You can also try withe Live555) 

Before discarting them i would check:
- Is latency due to your system? or it is due to the player? 
- Quality could be related to CPU performance issues or settings on the encoder. 
Perhaps try to stream using I frames only , even reducing frames/second and see if they look good this way. Perhaps you can downscale  the image first to encoding it. 

Not sure if RPI can do H264 encoding by HW? or if it is doing it by SW? this is another are to look at.
But as i said, your approach sounds correct. There is always the possibility that you use your own blocks, but that is a different project/discussion.

**Comment by JimKlingshirn** [comment]
The player usually adds a lot of latency.  In VLC you can minimize the
amount of packet buffering to remove most of the latency.

**Comment by vgrsystems** [comment]
Thanks a lot i will try that RegardsFrancois


Envoyé depuis Yahoo Mail pour iPhone


Le vendredi, août 31, 2018, 1:19 AM, Jim Klingshirn <notifications@github.com> a écrit :

The player usually adds a lot of latency. In VLC you can minimize the
amount of packet buffering to remove most of the latency.
